### ISSUE TITLE
AWS: ResourceNotFoundException

### ISSUE THREAD

**Issue by animista01** [dvalbuena1/visa_rescheduler_aws#23]
Hey I am getting this error on this line `response = scheduler_client.get_schedule(Name=event_arn)` Any idea?

```
[ERROR] ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetSchedule operation: Schedule visa-rescheduler-lambda-pro-MainEventsRuleSchedule1-SOME-ID does not exist.
Traceback (most recent call last):
  File "/var/task/handler.py", line 27, in lambda_handler
    response = scheduler_client.get_schedule(Name=event_arn)
  File "/var/lang/lib/python3.12/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lang/lib/python3.12/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
  ```

**Comment by dvalbuena1** [comment]
Looks like it cannot find the Scheduled created. 
Did you modify the `serverless.yml` in some way? That file is in charge of creating the resource in AWS.

I would recommend that you simply delete everything and re-deploy. Using `sls delete` and then `python -c "import setup; setup.as_loop()".`

**Comment by jrojas-qventus** [comment]
Did this work for you @animista01 ? check in the logs if the script is looking for a language pack if so then I will make a pull request to fix it (:
